### ISSUE TITLE
[Bug Report] Spotify support not working

### ISSUE THREAD

**Issue by Rainogo** [ErdbeerbaerLP/MusicBot#3]
### Bug Description

After properly setting my client ID and secret on the config file, the bot does search for the songs, but it won't play them.

### Steps to Reproduce

1. Download the .jar or compile from source code
2. Create an application on spotify
3. Set my client ID and secret on the config file
4. Use the command spsearch <name> or play <spotify url>
5. The bot finds the song but remains in silence

### Expected Result

Just play the music

### Debug Output

![failed](https://github.com/user-attachments/assets/8f56329e-d70f-496b-a6df-76444da3803a)

### Checklist

- [X] I have looked for information about this [within the documentation](https://jmusicbot.com/)
- [X] I have searched for similar issues [on the issues page](https://github.com/jagrosh/MusicBot/issues?q=is%3Aissue)
- [X] I am running the latest version of the bot: ![Release](https://img.shields.io/github/release/jagrosh/MusicBot.svg)

**Comment by ErdbeerbaerLP** [comment]
Is this still an issue with the new release file? I've updated the libraries and added login support

Note: it will now ask for logging in to youtube on first startup, use an alt account for that. Did not add a way to skip it (yet)
